command_timeout = 1000

# Appearance
format = """
$directory\
$all\
$fill\
$line_break\
$jobs\
$status\
$battery\
$character\
"""

right_format = """
$cmd_duration\
$time
"""

# Prompt
[fill]
symbol = "∙"
style = "dimmed"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[λ](bold green)"


# Technical information
[[battery.display]]
threshold = 25
style = "bold red"

[cmd_duration]
min_time = 10
show_milliseconds = true

[time]
disabled = false


# Modules
[directory]
truncation_length = 7
truncate_to_repo = true
style = "#E2CC44 bold"

[status]
format = "[$status]($style) "
disabled = false

[package]
disabled = true

[aws]
symbol = '  '
disabled = false

[aws.profile_aliases]
wolt-aws-merchantoncall_rw = 'merchantoncall_rw'
wolt-aws-merchantfoundations_rw = 'merchantfoundations_rw'
wolt-aws-merchantfoundations_ro = 'merchantfoundations_ro'

wolt-aws-dev-merchantoncall_rw = 'dev-merchantoncall_rw'
wolt-aws-dev-merchantfoundations_rw = 'dev-merchantfoundations_rw'
wolt-aws-dev-merchantfoundations_ro = 'dev-merchantfoundations_ro'

wolt-legacy-merchantfoundations_ro = 'legacy-merchantfoundations_ro'
wolt-legacy-merchantfoundations_rw = 'legacy-merchantfoundations_rw'
wolt-legacy-merchantoncall_rw = 'legacy-merchantoncall_rw'

[direnv]
disabled = false
format = 'via [$symbol]($style) $loaded '
style = 'bold green'
symbol = 'direnv'
loaded_msg = '✅'
unloaded_msg = '❌'

[docker_context]
disabled = true

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[git_status]
stashed = ""
ahead = ' ⇡${count}'
behind = ' ⇣${count}'

[nix_shell]
heuristic = true
symbol = ''
unknown_msg = 'ad-hoc'
format = 'via [$symbol $name]($style) '


# Languages, build tools, and ecosystems
[elm]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "
version_format = "v$major.$minor"

[java]
symbol = " "
version_format = "v${major}"
style = "bold fg:#ED8B00"

[nodejs]
symbol = " "

[kotlin]
symbol = " "
style = "bold fg:#B125EA"

[python]
symbol = ' '

[scala]
symbol = " "

[terraform]
symbol = ""
format = 'via [$symbol $version]($style) '
