[[snippets]]
prefix = "log"
body = 'console.log("$1")'

[[snippets]]
prefix = "EE"
body = 'Effect.Effect<$1>'

[[snippets]]
prefix = "LL"
body = 'Layer.Layer<$1>'

[[snippets]]
prefix = "Err"
body = '''
export class $1 {
    readonly _tag = '$1';
}'''

[[snippets]]
prefix = "gen"
body = '''
Effect.gen(function* () {
  $1
})'''

[[snippets]]
prefix = "tag"
body = '''
export interface $1 {
  $2
}

export const $1 = Context.Tag('$1')<$1, $1>();
'''
