[[snippets]]
prefix = "log"
body = 'console.log("$1")'

[[snippets]]
prefix = "EE"
body = 'Effect.Effect<$1>'

[[snippets]]
prefix = "OO"
body = 'Option.Option<$1>'

[[snippets]]
prefix = "LL"
body = 'Layer.Layer<$1>'

[[snippets]]
prefix = "TODO"
body = '''
return yield* Effect.dieMessage('TODO')
'''

[[snippets]]
prefix = "Err"
body = '''export class $1 extends Data.TaggedError('$1') {}'''

[[snippets]]
prefix = "gen"
body = '''
Effect.gen(function* () {
  $1
})'''

[[snippets]]
prefix = "tag"
body = '''
export interface $1 {
  readonly $2
}

export const $1 = Context.Tag('$1')<$1, $1>();
'''

[[snippets]]
prefix = "live"
body = '''
export namespace Live$1 {
  const layer = Layer.effect(
    $1,
    Effect.gen(function* () {
      return create()
    })
  )

  function create(): $1 {
    return $1.of({

    })
  }
}
'''
