command_timeout = 750

# Appearance
format = """
$directory\
$all\
$fill\
$line_break\
$jobs\
$status\
$battery\
$character\
"""

right_format = """
$cmd_duration\
$time
"""

# Prompt
[fill]
symbol = "∙"
style = "dimmed"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[λ](bold green)"


# Technical information
[[battery.display]]
threshold = 25
style = "bold red"

[cmd_duration]
min_time = 10
show_milliseconds = true

[time]
disabled = false


# Modules
[directory]
truncation_length = 7
truncate_to_repo = true
style = "#E2CC44 bold"

[status]
format = "[$status]($style) "
disabled = false

[direnv]
disabled = false
format = 'via [$symbol]($style)\($loaded\)'
style = 'bold green'
symbol = 'direnv'
loaded_msg = '✅'
unloaded_msg = '❌'

[docker_context]
symbol = '🐳'
format = 'via [$symbol]($style) '

[package]
disabled = true

[elm]
symbol = " "

[java]
style = "red bold"

[scala]
symbol = " "

[nix_shell]
heuristic = true
symbol = ''
unknown_msg = 'ad-hoc'
format = 'via [$symbol $name]($style) '
