theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
cursorline = true
color-modes = true
whitespace.render = "all"
bufferline = "always"
shell = ["fish", "-c"]

# Auto-completion
idle-timeout = 20
completion-timeout = 20
completion-trigger-len = 0
preview-completion-insert = false

# Width
text-width = 120
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "spinner", "diagnostics", "selections"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = [
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "separator",
  "spacer",
  "version-control",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = false

# ============================================ Keybinds ============================================
[keys.insert]
C-p = ["signature_help"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-p = ["signature_help"]

"X" = ["extend_line_above"]

# Select highlighted text for search
"*" = ["search_selection"]

# Select word at cursor for search
"C-*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
]

# Move lines up and down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

# Map + to host LSP commands
[keys.normal."+"]
r = ":lsp-restart"
s = ":lsp-stop"
l = ":lsp-workspace-command"
b = ":lsp-workspace-command compile-cascade" # Scala/Metals specific
i = ":lsp-workspace-command build-import"    # Scala/Metals specific

# Map ยง to host config toggling commmands
[keys.normal."ยง"]
f = ":toggle-option auto-format"
h = ":toggle-option file-picker.hidden"
g = ":toggle-option file-picker.git-ignore"
i = ":toggle-option lsp.display-inlay-hints"
w = ":toggle-option soft-wrap.enable"

# Map ' to host code/text modification commands
[keys.normal."'"]
f = ":format"
w = ":buffer-close"
W = ":buffer-close-others"
r = ":reload-all"
")" = "rotate_selection_contents_forward"
"(" = "rotate_selection_contents_backward"
s = ["split_selection_on_newline", ":sort"]
y = "yank_joined"
Y = "yank_joined_to_clipboard"
