tap "coursier/formulas"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask"
tap "homebrew/core"
tap "virtuslab/scala-cli"

# Dotfiles management
brew "chezmoi"

# Dev tools
brew "coursier/formulas/coursier"
brew "gh"
brew "git"
brew "nvm"
brew "sdkman-cli"
brew "virtuslab/scala-cli/scala-cli"
cask "dash"
cask "docker"
cask "jetbrains-toolbox"
cask "postman"
cask "visual-studio-code"

# CLI
brew "bat"
brew "curlie"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "gping"
brew "iperf3"
brew "jq"
brew "starship"
brew "tldr"
cask "font-fira-code-nerd-font"
cask "iterm2"

# Window/screen management
cask "alt-tab"
cask "monitorcontrol"
cask "rectangle"

# Productivity etc.
cask "firefox"
cask "google-chrome"
cask "karabiner-elements"
cask "notion"
cask "numi"
cask "signal"
cask "spotify"

# Misc
cask "aldente"
cask "appcleaner"
cask "bartender"
cask "stats"
