tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "coursier/formulas"
tap "virtuslab/scala-cli"


# Dotfiles management
brew "chezmoi"


# Dev tools
brew "git"
brew "gh"
brew "nvm"
brew "coursier/formulas/coursier"
brew "virtuslab/scala-cli/scala-cli"

cask "visual-studio-code"
cask "jetbrains-toolbox"
cask "dash"
cask "postman"


# Utilities
brew "iperf3"


# Productivity etc.
cask "rectangle"
cask "notion"
cask "google-chrome"
cask "firefox"
cask "signal"
cask "appcleaner"
