theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
whitespace.render = "all"
bufferline = "always"
shell = ["fish", "-c"]

# Auto-completion
idle-timeout = 50
preview-completion-insert = false
completion-trigger-len = 1

# Width
text-width = 120
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "spinner", "diagnostics", "selections"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = [
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "separator",
  "spacer",
  "version-control",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.smart-tab]
supersede-menu = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.insert]
C-p = ["signature_help"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-w = [":buffer-close"]
A-f = [":format"]
C-p = ["signature_help"]

"X" = ["extend_line_above"]

# Select highlighted text for search
"*" = ["search_selection"]

# Select word at cursor for search
"C-*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
]

# Move lines up and down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

# Map + to host LSP commands
[keys.normal."+"]
l = ":lsp-workspace-command"
b = ":lsp-workspace-command compile-cascade"
i = ":lsp-workspace-command build-import"

# Map '' to host config toggling commmands
[keys.normal."'"]
f = ":toggle-option auto-format"
h = ":toggle-option file-picker.hidden"
g = ":toggle-option file-picker.git-ignore"
i = ":toggle-option lsp.display-inlay-hints"
w = ":toggle-option soft-wrap.enable"

[keys.normal."ยง"]
s = ["split_selection_on_newline", ":sort"]
