# Appearance
format = """
$all\
$fill\
$line_break\
$battery\
$character\
"""

right_format = """
$cmd_duration\
$time
"""

[directory]
truncation_length = 7
truncate_to_repo = true
style = "#E2CC44 bold"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[➜](bold green)"

[fill]
symbol = "∙"
style = "dimmed"


# Technical information
[[battery.display]]
threshold = 25
style = "bold red"

[cmd_duration]
min_time = 0
show_milliseconds = true

[time]
disabled = false


# Modules
[package]
disabled = true

[elm]
symbol = " "

[java]
style = "red bold"

[scala]
symbol = " "
