theme = "onedark"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
rulers = [120]
bufferline = "always"
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render.space = "all"
render.tab = "all"
render.nbsp = "all"
render.newline = "none"

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "selections"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = ["position", "file-encoding", "file-line-ending", "file-type", "separator", "spacer", "version-control"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
