theme = "onedark"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
text-width = 120
rulers = [120]
bufferline = "always"
shell = ["fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render.space = "all"
render.tab = "all"
render.nbsp = "all"
render.newline = "none"

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "selections"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = [
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "separator",
  "spacer",
  "version-control",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-C-i = [":toggle lsp.display-inlay-hints"]
A-C-f = [":toggle auto-format"]

