# TODO Remove HOCON when PR gets merged: https://github.com/helix-editor/helix/pull/9203
[[language]]
name = "hocon"
scope = "source.conf"
file-types = ["conf"]
roots = []
comment-token = "#"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "hocon"
source = { git = "https://github.com/antosha417/tree-sitter-hocon", rev = "c390f10519ae69fdb03b3e5764f5592fb6924bcc" }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--stdin-filepath ", "dummy.css"] }
auto-format = true

[[language]]
name = "elm"
formatter = { command = "elm-format", args = ["--stdin "] }
auto-format = true

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = false

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.html"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.js"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.json"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.md"] }
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[[language]]
name = "nix"
formatter = { command = "nixfmt --width 120" }
auto-format = true

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "prisma"
auto-format = true

[[language]]
name = "protobuf"
formatter = { command = "zsh", args = [
  "-c",
  "clang-format",
  "--assume-filename=dummy.proto",
  "--style=file:$HOME/.config/.clang-format",
] } # In order to use variable expansion, the command must be run through shell, see: https://github.com/helix-editor/helix/issues/5538#issuecomment-1383197516
auto-format = true

[language-server.metals]
command = "metals"
config = { "isHttpEnabled" = true }
environment = { "SBT_TPOLECAT_DEV" = "1" }

[[language]]
name = "scala"
auto-format = true

[[grammar]]
name = "scala"
source = { git = "https://github.com/tree-sitter/tree-sitter-scala", rev = "7891815f42dca9ed6aeb464c2edc39d479ab965c" }


[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.scss"] }
auto-format = true

[[language]]
name = "sql"
formatter = { command = "pg_format" }
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.ts"] }
auto-format = true

[[language]]
name = "xml"
auto-format = true
language-servers = ["vscode-html-language-server"]

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--stdin-filepath ", "dummy.yaml"] }
auto-format = true
