theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
cursorline = true
color-modes = true
bufferline = "always"
shell = ["fish", "-c"]

# Auto-completion
idle-timeout = 50
preview-completion-insert = false
completion-trigger-len = 1

# Width
text-width = 120
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render.space = "all"
render.tab = "all"
render.nbsp = "all"
render.newline = "none"

[editor.statusline]
left = ["mode", "spacer", "spinner", "diagnostics", "selections"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = [
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "separator",
  "spacer",
  "version-control",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_start",
  "search_selection",
]
"C-*" = ["search_selection"]
A-w = [":buffer-close"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-C-i = [":toggle lsp.display-inlay-hints"]
A-C-f = [":toggle auto-format"]
A-G = [":toggle file-picker.git-ignore"]

[keys.normal."+"]
l = ":lsp-workspace-command"
b = ":lsp-workspace-command compile-cascade"
i = ":lsp-workspace-command build-import"
s = ["split_selection_on_newline", ":sort"]

[keys.insert]
C-p = ["signature_help"]
