# ------------------------------------------------- Language servers -------------------------------------------------
[language-server.copilot]
command = "helix-gpt"
args = ["--handler", "copilot"]

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 10     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true
feature_words = true
feature_snippets = true
feature_unicode_input = false

[language-server.scls.environment]
RUST_LOG = "info,simple-completion-langauge-server=info"
LOG_FILE = "/tmp/completion.log"


[language-server.metals]
command = "metals"
config = { "isHttpEnabled" = true }
environment = { "SBT_TPOLECAT_DEV" = "1" }


# ----------------------------------------------------- Languages -----------------------------------------------------

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--stdin-filepath ", "dummy.css"] }
auto-format = true
language-servers = ["vscode-css-language-server", "scls", "copilot"]

[[language]]
name = "elm"
formatter = { command = "elm-format", args = ["--stdin "] }
auto-format = true

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = false
# language-servers = ["fish-lsp"]
language-servers = ["scls", "copilot"]

[[language]]
name = "hcl"
auto-format = true
formatter = { command = "terraform", args = ["fmt", "-"] }
language-servers = ["terraform-ls", "scls", "copilot"]

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.html"] }
auto-format = true
language-servers = ["vscode-html-language-server", "scls", "copilot"]

[[language]]
name = "java"
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.js"] }
auto-format = true
language-servers = ["typescript-language-server", "scls", "copilot"]

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.json"] }
auto-format = true
language-servers = ["vscode-json-language-server", "scls", "copilot"]

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.md"] }
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
language-servers = ["marksman", "scls", "copilot"]

[[language]]
name = "nix"
formatter = { command = "nixfmt", args = ["--width", "120"] }
auto-format = true
language-servers = ["nil", "scls", "copilot"]

[[language]]
name = "prisma"
auto-format = true
language-servers = ["prisma-language-server", "scls", "copilot"]

[[language]]
name = "protobuf"
language-servers = ["bufls", "pbkit", "scls", "copilot"]
formatter = { command = "zsh", args = [
  "-c",
  "clang-format",
  "--assume-filename=dummy.proto",
  "--style=file:$HOME/.config/.clang-format",
] } # In order to use variable expansion, the command must be run through shell, see: https://github.com/helix-editor/helix/issues/5538#issuecomment-1383197516
auto-format = true

[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
language-servers = ["pylsp", "scls", "copilot"]

[[language]]
name = "scala"
auto-format = true
language-servers = ["metals", "scls", "copilot"]

[[language]]
name = "scheme"
language-servers = ["copilot"]

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.scss"] }
auto-format = true
language-servers = ["vscode-css-language-server", "scls", "copilot"]

[[language]]
name = "sql"
formatter = { command = "pg_format" }
auto-format = true
language-servers = ["scls", "copilot"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo", "scls", "copilot"]

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.ts"] }
auto-format = true
language-servers = ["typescript-language-server", "scls", "copilot"]

[[language]]
name = "xml"
auto-format = true
language-servers = ["vscode-html-language-server", "scls", "copilot"]

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.yaml"] }
auto-format = true
language-servers = [
  "yaml-language-server",
  "ansible-language-server",
  "scls",
  "copilot",
]
